### PR TITLE
fix: fix non helmified projects

### LINKED ISSUE #26: _Helm_ version analyzer raise error when project is not _helmified_ in the old revision
When _helm_ version analyzer tries to find `Chart.yaml` file in the old revision, since that revision hasn't been _helmified_, it raises the following error:
```
time="${TIMESTAMP}" level=panic msg="open ${HELM_ROOT_DIR}/Chart.yaml: no such file or directory"
```

### PR DESCRIPTION
**Pull request by Adibov**
Closes #26.

### CODE REVIEW

File: internal/models/versionanalyzers/helm_version_analyzer.go [hunk 1]
```diff
@@ -57,6 +58,9 @@ type helmChart struct {
 
 func (a *HelmVersionAnalyzer) ReadVersion(projectRootDir string, extraArgs *models.ArgumentValues) (string, error) {
 	rootDir := filepath.Join(projectRootDir, *(*extraArgs)[HelmArgumentKeyRootDir])
+	if _, err := os.Stat(filepath.Join(rootDir, "Chart.yaml")); errors.Is(err, os.ErrNotExist) {
+		return "0.0.0", nil
```
Comment (emranbm) [inline internal/models/versionanalyzers/helm_version_analyzer.go]: Isn't it better to return an empty string and update the `NeedsVersionUpdate` logic?

Comment (emranbm) [inline internal/models/versionanalyzers/helm_version_analyzer.go]: Please also `log.info` here.

**Review by emranbm — CHANGES_REQUESTED** [review]

File: internal/models/versionanalyzers/helm_version_analyzer.go (hunk 1 above)
Comment (Adibov) [reply internal/models/versionanalyzers/helm_version_analyzer.go]: Nice point.

Comment (Adibov) [reply internal/models/versionanalyzers/helm_version_analyzer.go]: I put log in `CompareVersions` function.

File: internal/models/versionanalyzers/helm_version_analyzer_test.go [hunk 2]
```diff
@@ -116,3 +116,13 @@ func (s *HelmVersionAnalyzerTestSuite) TestVersionUpdateIsNeededWhenSomeChangesA
...
 }
+
+func (s *HelmVersionAnalyzerTestSuite) TestNonHelmifiedRevision() {
+	s.NoError(os.MkdirAll("./test-dir", os.ModePerm))
+	helmRootDir := "./test-dir"
+	version := utils.GetResultOrPanic(s.helmVersionAnalyzer.ReadVersion(".", &models.ArgumentValues{
+		HelmArgumentKeyRootDir: &helmRootDir,
+	}))
+	s.Equal("", version)
+	s.NoError(os.RemoveAll("./test-dir"))
```
Comment (emranbm) [inline internal/models/versionanalyzers/helm_version_analyzer_test.go]: Use teardown for such cleanings. Since this line may not run when a previous assertion fails.

**Review by emranbm — CHANGES_REQUESTED** [review]

**Review by emranbm — APPROVED** [review]
LGTM
